myshop/cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:p_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:p_id>/', views.cart_remove, name='cart_remove'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('favorite/', include(('favorite.urls', 'favorite'), namespace='favorite')),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('create/', views.order_create, name="order_create"),
]

myshop/shop/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('about/', views.about, name='about'),
    path('delivery/', views.delivery, name='delivery'),
    path('contacts/', views.contacts, name='contacts'),
    path('discounts/', views.discounts, name='discounts'),
    path('fandoms/', views.fandom_list, name='fandom_list'),
    path('popular/', views.popular_list, name='popular_list'),
    path('add-rating/', views.add_rating, name='add_rating'),
    re_path(r'^fandoms/(?P<fandom_slug>[-\w]+)/$', views.fandom_list, name='product_list_by_fandom'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    re_path(r'^popular/$', views.popular_list, name='price_filter_by_popular'),
    re_path(r'^fandoms/(?P<fandom_slug>[-\w]+)/$', views.fandom_list, name='price_filter_by_fandom'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='price_filter_by_category'),
    re_path(r'^$', views.product_list, name='search'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

myshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label="Количество"
    )
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myshop/cart/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect
from shop.models import Product, Category
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, p_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=p_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd["quantity"], update_quantity=cd["update"])
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def cart_remove(request, p_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=p_id)
    cart.remove(product)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def cart_detail(request):
    categories = Category.objects.all()
    cart = Cart(request)
    return render(request, "cart/detail.html", {"categories": categories, "cart": cart})

myshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Корзина
{% endblock %}
{% block content %}

<div class="container content">
    {% if cart.len == 0 %}<h1>Корзина, кажется, пустая. Давай наполним ее чем-то интересным!</h1>
    <a href="{% url "shop:product_list" %}" class="btn btn-secondary btn-lg">За покупками</a>
    {% else %}
    <h1>Ваша корзина</h1>
    <div class="row">
        <table class="table table-striped table-light">
            <thead>
            <tr class="text-center">
                <th>Изображение</th>
                <th>Название</th>
                <th>Количество</th>
                <th>Цена товара</th>
                <th>Удалить</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart %}
                {% with p=item.product %}
                    <tr class="text-center">
                        <td>
                            <a href="{{ p.get_absolute_url }}">
                                <img src="{% if p.image %}{{ p.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" style="max-height: 100px;">
                            </a>
                        </td>
                        <td style="vertical-align: middle">{{ p.name }}</td>
                        <td style="vertical-align: middle">{{ item.quantity }}</td>
                        <td style="vertical-align: middle">{{ p.price }}р.</td>
                        <td style="vertical-align: middle"><a class="text-dark" href="{% url 'cart:cart_remove' p.id %}">Удалить товар</a></td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>Итого:</td>
                <td colspan="3"></td>
                <td class="num">{{ cart.get_total_price }}р.</td>
            </tr>
            </tbody>
        </table>
    </div>
        
    <p class="text-right">
        <a href="{% url "shop:product_list" %}" class="btn btn-secondary btn-lg">Продолжить покупки</a>
        <a href="{% url "orders:order_create" %}" class="btn btn-secondary btn-lg">Оформить заказ</a>
    </p>
    {% endif %}
</div>

{% endblock %}