myshop/cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:p_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:p_id>/', views.cart_remove, name='cart_remove'),
]

myshop/favorite/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.favorite_detail, name='favorite_detail'),
    path('add/<int:product_id>/', views.favorite_add, name='favorite_add'),
    path('remove/<int:product_id>/', views.favorite_remove, name='favorite_remove'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('favorite/', include(('favorite.urls', 'favorite'), namespace='favorite')),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('about/', views.about, name='about'),
    path('delivery/', views.delivery, name='delivery'),
    path('contacts/', views.contacts, name='contacts'),
    path('discounts/', views.discounts, name='discounts'),
    path('fandoms/', views.fandom_list, name='fandom_list'),
    path('popular/', views.popular_list, name='popular_list'),
    path('add-rating/', views.add_rating, name='add_rating'),
    re_path(r'^fandoms/(?P<fandom_slug>[-\w]+)/$', views.fandom_list, name='product_list_by_fandom'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    re_path(r'^popular/$', views.popular_list, name='price_filter_by_popular'),
    re_path(r'^fandoms/(?P<fandom_slug>[-\w]+)/$', views.fandom_list, name='price_filter_by_fandom'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='price_filter_by_category'),
    re_path(r'^$', views.product_list, name='search'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

myshop/favorite/models.py
from django.db import models

# Create your models here.

myshop/favorite/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class FavoriteAddProductForm(forms.Form):
    quantity = 1
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myshop/favorite/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect
from shop.models import Product, Category
from .favorite import Favorite
from .forms import FavoriteAddProductForm


@require_POST
def favorite_add(request, product_id):
    favorite = Favorite(request)
    product = get_object_or_404(Product, id=product_id)
    form = FavoriteAddProductForm(request.POST)
    if form.is_valid():
        favorite.add(product=product)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def favorite_remove(request, product_id):
    favorite = Favorite(request)
    product = get_object_or_404(Product, id=product_id)
    favorite.remove(product)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def favorite_detail(request):
    categories = Category.objects.all()
    favorite = Favorite(request)
    return render(request, 'favorite/detailfav.html', {"categories": categories, 'favorite': favorite})

myshop/favorite/templates/favorite/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Избранное
{% endblock %}
{% block content %}

<div class="container content">
    {% if favorite.len == 0 %}<h1>Тут пусто! :(</h1>
    <a href="{% url "shop:product_list" %}" class="btn btn-secondary btn-lg">За покупками</a>
    {% else %}
    <h1>Избранные товары</h1>
    <div class="row">
        <table class="table table-striped table-light">
            <thead>
            <tr class="text-center">
                <th>Изображение</th>
                <th>Название</th>
                <th>Цена товара</th>
                <th>Удалить</th>
            </tr>
            </thead>
            <tbody>
            {% for item in favorite %}
                {% with product=item.product %}
                    <tr class="text-center">
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" style="max-height: 100px;">
                            </a>
                        </td>
                        <td style="vertical-align: middle">{{ product.name }}</td>
                        <td style="vertical-align: middle">{{ item.price }}р.</td>
                        <td style="vertical-align: middle"><a class="text-dark" href="{% url 'favorite:favorite_remove' product.id%}">Удалить товар</a></td>
                    </tr>
                {% endwith %}
            {% endfor %}
            </tbody>
        </table>
    </div>
        
    <p class="text-right">
        <a href="{% url "shop:product_list" %}" class="btn btn-warning btn-lg">Продолжить покупки</a>
    </p>
    {% endif %}
</div>
{% endblock %}

myshop/favorite/templates/favorite/detailfav.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Избранное
{% endblock %}
{% block content %}

<div class="container content">
    {% if favorite.len == 0 %}<h1>Тут пусто! :(</h1>
    <a href="{% url "shop:product_list" %}" class="btn btn-secondary btn-lg">За покупками</a>
    {% else %}
    <h1>Избранные товары</h1>
    <div class="row">
        <table class="table table-striped table-light">
            <thead>
            <tr class="text-center">
                <th>Изображение</th>
                <th>Название</th>
                <th>Цена товара</th>
                <th>Удалить</th>
            </tr>
            </thead>
            <tbody>
            {% for item in favorite %}
                {% with product=item.product %}
                    <tr class="text-center">
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" style="max-height: 100px;">
                            </a>
                        </td>
                        <td style="vertical-align: middle">{{ product.name }}</td>
                        <td style="vertical-align: middle">{{ product.price }}р.</td>
                        <td style="vertical-align: middle"><a class="text-dark" href="{% url 'favorite:favorite_remove' product.id %}">Удалить товар</a></td>
                    </tr>
                {% endwith %}
            {% endfor %}
            </tbody>
        </table>
    </div>
        
    <p class="text-right">
        <a href="{% url 'shop:product_list' %}" class="btn btn-secondary btn-lg">Продолжить покупки</a>
    </p>
    {% endif %}
</div>
{% endblock %}