myshop/cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:p_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:p_id>/', views.cart_remove, name='cart_remove'),
]

myshop/favorite/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.favorite_detail, name='favorite_detail'),
    path('add/<int:product_id>/', views.favorite_add, name='favorite_add'),
    path('remove/<int:product_id>/', views.favorite_remove, name='favorite_remove'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('favorite/', include(('favorite.urls', 'favorite'), namespace='favorite')),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('about/', views.about, name='about'),
    path('delivery/', views.delivery, name='delivery'),
    path('contacts/', views.contacts, name='contacts'),
    path('discounts/', views.discounts, name='discounts'),
    path('fandoms/', views.fandom_list, name='fandom_list'),
    path('popular/', views.popular_list, name='popular_list'),
    path('add-rating/', views.add_rating, name='add_rating'),
    re_path(r'^fandoms/(?P<fandom_slug>[-\w]+)/$', views.fandom_list, name='product_list_by_fandom'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    re_path(r'^popular/$', views.popular_list, name='price_filter_by_popular'),
    re_path(r'^fandoms/(?P<fandom_slug>[-\w]+)/$', views.fandom_list, name='price_filter_by_fandom'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='price_filter_by_category'),
    re_path(r'^$', views.product_list, name='search'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

myshop/shop/models.py
from itertools import product
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField("Имя", max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args=[self.slug])


class Fandom(models.Model):
    name = models.CharField("Имя", max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name = "Фандом"
        verbose_name_plural = "Фандомы"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_list_by_fandom", args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name="products")
    fandom = models.ForeignKey('Fandom', on_delete=models.CASCADE, related_name="fan_prod")
    name = models.CharField("Имя", max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("name",)
        index_together = (("id", "slug"),)
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id, self.slug])


class RatingStar(models.Model):
    """Звезда рейтинга"""
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]


class Rating(models.Model):
    """Рейтинг"""
    ip = models.CharField("IP адрес", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="Звезда")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Товар")

    def __str__(self):
        return f"{self.star} - {self.product}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"

    
class Response(models.Model):
    name = models.CharField("Имя", max_length=200)
    comment = models.TextField("Комментарий")
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.comment[0:200]

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

myshop/shop/forms.py
from django import forms
from .models import Rating, RatingStar, Response

class ResponseForm(forms.ModelForm):
    class Meta:
        model = Response
        fields = ('name', 'comment',)


class RatingForm(forms.ModelForm):
    """Форма добавления рейтинга"""
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("star",)

myshop/shop/views.py
from unittest import result
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.http import require_POST
from .models import Category, Fandom, Product, Rating, Response
from cart.forms import CartAddProductForm
from favorite.forms import FavoriteAddProductForm
from .forms import RatingForm, ResponseForm
import operator


def about(request):    
    categories = Category.objects.all()
    comments = Response.objects.filter(active=True)
    print(comments)
    if request.method == "POST":
        form = ResponseForm(request.POST)
        if form.is_valid():
            comment = form.save()
            return render(request, "shop/information/about.html", {"categories": categories, "comments": comments, "comment": comment})
    else:
        form = ResponseForm
    return render(request, "shop/information/about.html", {"categories": categories, "comments": comments, "form": form})

def delivery(request):    
    categories = Category.objects.all()
    return render(request, "shop/information/delivery.html", {"categories": categories})

def contacts(request):    
    categories = Category.objects.all()
    return render(request, "shop/information/contacts.html", {"categories": categories})

def discounts(request):    
    categories = Category.objects.all()
    return render(request, "shop/information/discounts.html", {"categories": categories})


def price_filter(request, ids):
    categories = Category.objects.all()
    print(ids + 'a')
    products = Product.objects.filter(id__in=ids)
    min_price = request.GET["min_price"]
    max_price = request.GET["max_price"]
    results = products.filter(price__range=(int(min_price), int(max_price)))

    return render(request, "shop/product/fandoms.html", {"categories": categories, "results": results, "ids": ids},)


def fandom_list(request, fandom_slug=None):
    categories = Category.objects.all()
    fandom = None
    fandoms = Fandom.objects.all()
    products = Product.objects.filter(available=True)
    results = []
    if fandom_slug:
        fandom = get_object_or_404(Fandom, slug=fandom_slug)
        products = products.filter(fandom=fandom)
        if request.GET.get("min_price") and request.GET.get("max_price"):
            min_price = request.GET["min_price"]
            max_price = request.GET["max_price"]
            results = products.filter(price__range=(int(min_price), int(max_price)))
            if not results:
                products = None

    return render(request, "shop/product/fandoms.html", {"categories": categories, "fandom": fandom, "fandoms": fandoms, "results": results, "products": products},)

def popular_list(request):
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    popular = Rating.objects.all().order_by('-star').values('product')[:6]
    ids = []
    results = []
    for elem in popular:
        ids.append(elem.get('product', None))
    products = products.filter(id__in=ids)

    if request.GET.get("min_price") and request.GET.get("max_price"):
        min_price = request.GET["min_price"]
        max_price = request.GET["max_price"]
        results = products.filter(price__range=(int(min_price), int(max_price)))
        if not results:
            products = None

    return render(request, "shop/product/popular.html", {"categories": categories, "results": results, "products": products,})


def product_list(request, category_slug=None):
    category = None
    ordered = None
    categories = Category.objects.all()
    popular = Rating.objects.all().order_by('-star').values('product')[:6]
    ids = []
    for elem in popular:
        ids.append(elem.get('product', None))
    products = Product.objects.filter(id__in=ids, available=True)
    query = None
    results_search = []
    results = []

    if request.GET.get("search"):
        query = request.GET["search"]
        results_search = Product.objects.filter(name__iregex=query)
        products = None

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)
        ordered = sorted(products, key=operator.attrgetter('name'))
        if request.GET.get("min_price") and request.GET.get("max_price"):
            min_price = request.GET["min_price"]
            max_price = request.GET["max_price"]
            results = products.filter(price__range=(int(min_price), int(max_price)))
            if not results:
                products = None
                ordered = None

    return render(
        request,
        "shop/product/list.html",
        {
            "category": category,
            "categories": categories,
            "products": products,
            "query": query,
            "results_search": results_search,
            "results": results,
            "ordered": ordered
        },
    )


def product_detail(request, id, slug):
    categories = Category.objects.all()
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    rating_stars = Rating.objects.filter(product=product).values('star')
    cart_product_form = CartAddProductForm()
    favorite_product_form = FavoriteAddProductForm()
    star_form = RatingForm()
    sum = 0
    for elem in rating_stars:
        sum += elem.get('star', None)
    if sum != 0:
        avg = round(float(sum/len(rating_stars)), 2)
    else:
        avg = 0
    return render(
        request,
        "shop/product/detail.html",
        {"categories": categories, "product": product, "cart_product_form": cart_product_form, "favorite_product_form": favorite_product_form, "star_form": star_form, "avg": avg},
    )


@require_POST
def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def add_rating(request):
    form = RatingForm(request.POST)
    if form.is_valid():
        Rating.objects.update_or_create(
            ip=get_client_ip(request),
            product_id=int(request.POST.get("product")),
            defaults={'star_id': int(request.POST.get("star"))}
        )
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        return HttpResponse(status=400)

myshop/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
<div class="container">
    <button type="button" value="Previous Page" class="btn btn-secondary btn-lg" onClick="window.history.back();">
        Назад
    </button>
    <div class="row" style="margin-top: 5%; margin-bottom: 10%;">
        <div class="col-sm-12 col-lg-5">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="" style="width: 100%;">
        </div>
        <div class="col-lg-7 col-sm-11">
            <h1>{{ product.name }}</h1>
            <br>
            <p>{{ product.description | safe }}</p>
            <p class="price h3">Цена: {{ product.price }}р.</p>

            <form action="{% url 'shop:add_rating' %}" method="post" name="rating">
                <b>Оценка:</b>
                {% csrf_token %}
                <input type="hidden" value="{{ product.id }}" name="product">
                <span class="rating">
                    {% for k, v in star_form.fields.star.choices %}
                        <input id="rating{{ v }}" type="radio" name="star" value="{{ k }}">
                        <label for="rating{{ v }}">{{ k }}</label>
                    {% endfor %}
                </span><br>
                <b>Рейтинг:</b>
                <span class="editContent">{{ avg }}</span>
            </form>

            <div style="margin-top: 3%;">
                <form action="{% url "favorite:favorite_add" product.id %}" method="post" class="float-sm-right" style="margin-top: 8px;">
                    {% csrf_token %}
                    {{ favorite_product_form }}
                    <br><input type="submit" value="Добавить в избранное" class="btn btn-secondary">
                </form>

                <form action="{% url "cart:cart_add" product.id %}" method="post" class="float-sm-right" style="margin-right: 5%;">
                    {% csrf_token %}
                    {{ cart_product_form }}
                    <br><input type="submit" value="Добавить в корзину" class="btn btn-secondary">
                </form>
            </div>
        </div>
    </div>
</div>
    

{% endblock %}

myshop/shop/templates/shop/product/fandoms.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if fandom %}{{ fandom.name }}{% else %}Фандомы{% endif %}
{% endblock %}
{% block content %}

<div class="container content">
    <div class="col-sm-12">
        {% if fandom %}
            {% if results %}
            <h3>{{ fandom.name }}</h3>
            <form action="{% url 'shop:price_filter_by_fandom' fandom.slug %}" method="get">
                <br><h5>Цена</h5>
                {% csrf_token %}
                <input placeholder="от" style="width: 10%;" name="min_price" type="" name="min_price" value="{{ min_price }}">
                <input placeholder="до" style="width: 10%;" name="max_price" type="" name="max_price" value="{{ max_price }}">
                <input type="submit" value="Показать">
            </form><br>
            <h3>Результаты</h3>
            <div class="row">
                {% for product in results %}
                    <div class="card bg-light" style="width: 32%; margin: 0.6%;">
                        <a href="{{ product.get_absolute_url }}"><img class="card-img-top" style="width:100%" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="изображение продукта"></a>
                        <div class="card-body text-center">
                            <a href="{{ product.get_absolute_url }}" class="card-title text-dark">{{ product.name }}</a><br>
                            <p class="card-text">{{product.price}}р.</p>
                            <a href="{{ product.get_absolute_url }}" class="btn btn-secondary">Подробнее</a>
                        </div>
                    </div>
                {% endfor %}
            </div>

            {% elif products %}
            <h3>{{ fandom.name }}</h3>
            <form action="{% url 'shop:price_filter_by_fandom' fandom.slug %}" method="get">
                <br><h5>Цена</h5>
                {% csrf_token %}
                <input placeholder="от" style="width: 10%;" name="min_price" type="" name="min_price" value="{{ min_price }}">
                <input placeholder="до" style="width: 10%;" name="max_price" type="" name="max_price" value="{{ max_price }}">
                <input type="submit" value="Показать">
            </form><br>
            <div class="row">
                {% for product in products %}
                    <div class="card bg-light" style="width: 32%; margin: 0.6%;">
                        <a href="{{ product.get_absolute_url }}"><img class="card-img-top" style="width:100%" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="изображение продукта"></a>
                        <div class="card-body text-center">
                            <a href="{{ product.get_absolute_url }}" class="card-title text-dark">{{ product.name }}</a><br>
                            <a href="{{ product.get_absolute_url }}" class="btn btn-secondary">Подробнее</a>
                            <p class="card-text">{{product.price}}р.</p>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <h3>По вашему запросу нет результатов</h3>
            {% endif %}
        </div>
    </div>

    {% else %}
    <h3>Фандомы</h3>
        <ul style="columns:3;">
            {% for f in fandoms %}
                <li class="list-group-item" {% if fandom.slug == f.slug %}class="selected"{% endif %}>
                    <a href="{{ f.get_absolute_url }}" class="text-dark">{{ f.name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
</div>
{% endblock %}

myshop/shop/templates/shop/product/favorites_detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
<div class="container content">
    <ul>
        {% for item in cart %}
        {% with product=item.product %}
        <li>
            <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
            </a>
        </li>
        {% endwith %}
        {% endfor %}
    </ul>
</div>
{% endblock %}

myshop/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}

<div class="container content">
    <div class="col-sm-12">
        {% if category and products %}
        <h3>{{ category.name }}</h3>
        <form action="{% url 'shop:price_filter_by_category' category.slug %}" method="get">
            <br><h5>Цена</h5>
            {% csrf_token %}
            <input placeholder="от" style="width: 10%;" name="min_price" type="" name="min_price" value="{{ min_price }}">
            <input placeholder="до" style="width: 10%;" name="max_price" type="" name="max_price" value="{{ max_price }}">
            <input type="submit" value="Показать">
        </form><br>
            {% if results %}
            <h3>Результаты</h3>
            <div class="row">
                {% for product in results %}
                    <div class="card bg-light" style="width: 32%; margin: 0.6%;">
                        <a href="{{ product.get_absolute_url }}"><img class="card-img-top" style="width:100%" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="изображение продукта"></a>
                        <div class="card-body text-center">
                            <a href="{{ product.get_absolute_url }}" class="card-title text-dark">{{ product.name }}</a><br>
                            <p class="card-text">{{product.price}}р.</p>
                            <a href="{{ product.get_absolute_url }}" class="btn btn-secondary">Подробнее</a>
                        </div>
                    </div>
                {% endfor %}
            </div>

            {% else %}
            <div class="row">
                {% for product in ordered %}
                    <div class="card bg-light" style="width: 32%; margin: 0.6%;">
                        <a href="{{ product.get_absolute_url }}"><img class="card-img-top" style="width:100%" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="изображение продукта"></a>
                        <div class="card-body text-center">
                            <a href="{{ product.get_absolute_url }}" class="card-title text-dark">{{ product.name }}</a><br>
                            <p class="card-text">{{product.price}}р.</p>
                            <a href="{{ product.get_absolute_url }}" class="btn btn-secondary">Подробнее</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% endif %}

        {% elif query and results_search %}
        <h3>Результаты по вашему запросу "{{ query }}"</h3>
        <div class="row">
            {% for product in results_search %}
                <div class="card bg-light" style="width: 32%; margin: 0.6%;">
                    <a href="{{ product.get_absolute_url }}"><img class="card-img-top" style="width:100%" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="изображение продукта"></a>
                    <div class="card-body text-center">
                        <a href="{{ product.get_absolute_url }}" class="card-title text-dark">{{ product.name }}</a><br>
                        <p class="card-text">{{product.price}}р.</p>
                        <a href="{{ product.get_absolute_url }}" class="btn btn-secondary">Подробнее</a>
                    </div>
                </div>
            {% endfor %}
        </div>

        {% elif products %}
        <div id="anime" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ul class="carousel-indicators">
                <li data-target="#anime" data-slide-to="0" class="active"></li>
                <li data-target="#anime" data-slide-to="1"></li>
                <li data-target="#anime" data-slide-to="2"></li>
            </ul>
            <!-- The slideshow -->
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'img/raiden.jpg' %}" alt="" width="100%" height="500">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'img/yaemiko.jpg' %}" alt="" width="100%" height="500">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'img/cats.jpg' %}" alt="" width="100%" height="500">
                </div>
            </div>
            <!-- Left and right controls -->
            <a class="carousel-control-prev" href="#anime" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#anime" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>
        <br>
        <h3>Популярное</h3>
        <div class="row">
            {% for product in products %}
                <div class="card bg-light" style="width: 32%; margin: 0.6%;">
                    <a href="{{ product.get_absolute_url }}"><img class="card-img-top" style="width:100%" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="изображение продукта"></a>
                    <div class="card-body text-center">
                        <a href="{{ product.get_absolute_url }}" class="card-title text-dark">{{ product.name }}</a><br>
                        <p class="card-text">{{product.price}}р.</p>
                        <a href="{{ product.get_absolute_url }}" class="btn btn-secondary">Подробнее</a>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% else %}
        <h3>По вашему запросу нет результатов</h3>
    </div>
{% endif %}
</div>
{% endblock %}

myshop/shop/templates/shop/product/popular.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Популярное
{% endblock %}
{% block content %}

<div class="container content">
    {% if results %}
        <h3>Популярное</h3>
        <form action="{% url 'shop:price_filter_by_popular' %}" method="get">
            <br><h5>Цена</h5>
            {% csrf_token %}
            <input placeholder="от" style="width: 10%;" name="min_price" type="" name="min_price" value="{{ min_price }}">
            <input placeholder="до" style="width: 10%;" name="max_price" type="" name="max_price" value="{{ max_price }}">
            <input type="submit" value="Показать">
        </form><br>
        <h3>Результаты</h3>
        <div class="row">
            {% for product in results %}
                <div class="card bg-light" style="width: 32%; margin: 0.6%;">
                    <a href="{{ product.get_absolute_url }}"><img class="card-img-top" style="width:100%" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="изображение продукта"></a>
                    <div class="card-body text-center">
                        <a href="{{ product.get_absolute_url }}" class="card-title text-dark">{{ product.name }}</a><br>
                        <p class="card-text">{{product.price}}р.</p>
                        <a href="{{ product.get_absolute_url }}" class="btn btn-secondary">Подробнее</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% elif products %}
        <h3>Популярное</h3>
        <form action="{% url 'shop:price_filter_by_popular' %}" method="get">
            <br><h5>Цена</h5>
            {% csrf_token %}
            <input placeholder="от" style="width: 10%;" name="min_price" type="" name="min_price" value="{{ min_price }}">
            <input placeholder="до" style="width: 10%;" name="max_price" type="" name="max_price" value="{{ max_price }}">
            <input type="submit" value="Показать">
        </form>
        <div class="row">
            {% for product in products %}
                <div class="card bg-light" style="width: 32%; margin: 0.6%;">
                    <a href="{{ product.get_absolute_url }}"><img class="card-img-top" style="width:100%" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="изображение продукта"></a>
                    <div class="card-body text-center">
                        <a href="{{ product.get_absolute_url }}" class="card-title text-dark">{{ product.name }}</a><br>
                        <p class="card-text">{{product.price}}р.</p>
                        <a href="{{ product.get_absolute_url }}" class="btn btn-secondary">Подробнее</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h3>По вашему запросу нет результатов</h3>
    {% endif %}
</div>
{% endblock %}