myshop/cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:p_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:p_id>/', views.cart_remove, name='cart_remove'),
]

myshop/favorite/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.favorite_detail, name='favorite_detail'),
    path('add/<int:product_id>/', views.favorite_add, name='favorite_add'),
    path('remove/<int:product_id>/', views.favorite_remove, name='favorite_remove'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('favorite/', include(('favorite.urls', 'favorite'), namespace='favorite')),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('about/', views.about, name='about'),
    path('delivery/', views.delivery, name='delivery'),
    path('contacts/', views.contacts, name='contacts'),
    path('discounts/', views.discounts, name='discounts'),
    path('fandoms/', views.fandom_list, name='fandom_list'),
    path('popular/', views.popular_list, name='popular_list'),
    path('add-rating/', views.add_rating, name='add_rating'),
    re_path(r'^fandoms/(?P<fandom_slug>[-\w]+)/$', views.fandom_list, name='product_list_by_fandom'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    re_path(r'^popular/$', views.popular_list, name='price_filter_by_popular'),
    re_path(r'^fandoms/(?P<fandom_slug>[-\w]+)/$', views.fandom_list, name='price_filter_by_fandom'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='price_filter_by_category'),
    re_path(r'^$', views.product_list, name='search'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

myshop/shop/models.py
from itertools import product
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField("Имя", max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args=[self.slug])


class Fandom(models.Model):
    name = models.CharField("Имя", max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name = "Фандом"
        verbose_name_plural = "Фандомы"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_list_by_fandom", args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name="products")
    fandom = models.ForeignKey('Fandom', on_delete=models.CASCADE, related_name="fan_prod")
    name = models.CharField("Имя", max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("name",)
        index_together = (("id", "slug"),)
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id, self.slug])


class RatingStar(models.Model):
    """Звезда рейтинга"""
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]


class Rating(models.Model):
    """Рейтинг"""
    ip = models.CharField("IP адрес", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="Звезда")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Товар")

    def __str__(self):
        return f"{self.star} - {self.product}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"

    
class Response(models.Model):
    name = models.CharField("Имя", max_length=200)
    comment = models.TextField("Комментарий")
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.comment[0:200]

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

myshop/shop/forms.py
from django import forms
from .models import Rating, RatingStar, Response

class ResponseForm(forms.ModelForm):
    class Meta:
        model = Response
        fields = ('name', 'comment',)


class RatingForm(forms.ModelForm):
    """Форма добавления рейтинга"""
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("star",)

myshop/shop/views.py
from unittest import result
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.http import require_POST
from .models import Category, Fandom, Product, Rating, Response
from cart.forms import CartAddProductForm
from favorite.forms import FavoriteAddProductForm
from .forms import RatingForm, ResponseForm
import operator


def about(request):    
    categories = Category.objects.all()
    comments = Response.objects.filter(active=True)
    print(comments)
    if request.method == "POST":
        form = ResponseForm(request.POST)
        if form.is_valid():
            comment = form.save()
            return render(request, "shop/information/about.html", {"categories": categories, "comments": comments, "comment": comment})
    else:
        form = ResponseForm
    return render(request, "shop/information/about.html", {"categories": categories, "comments": comments, "form": form})

def delivery(request):    
    categories = Category.objects.all()
    return render(request, "shop/information/delivery.html", {"categories": categories})

def contacts(request):    
    categories = Category.objects.all()
    return render(request, "shop/information/contacts.html", {"categories": categories})

def discounts(request):    
    categories = Category.objects.all()
    return render(request, "shop/information/discounts.html", {"categories": categories})


def price_filter(request, ids):
    categories = Category.objects.all()
    print(ids + 'a')
    products = Product.objects.filter(id__in=ids)
    min_price = request.GET["min_price"]
    max_price = request.GET["max_price"]
    results = products.filter(price__range=(int(min_price), int(max_price)))

    return render(request, "shop/product/fandoms.html", {"categories": categories, "results": results, "ids": ids},)


def fandom_list(request, fandom_slug=None):
    categories = Category.objects.all()
    fandom = None
    fandoms = Fandom.objects.all()
    products = Product.objects.filter(available=True)
    results = []
    if fandom_slug:
        fandom = get_object_or_404(Fandom, slug=fandom_slug)
        products = products.filter(fandom=fandom)
        if request.GET.get("min_price") and request.GET.get("max_price"):
            min_price = request.GET["min_price"]
            max_price = request.GET["max_price"]
            results = products.filter(price__range=(int(min_price), int(max_price)))
            if not results:
                products = None

    return render(request, "shop/product/fandoms.html", {"categories": categories, "fandom": fandom, "fandoms": fandoms, "results": results, "products": products},)

def popular_list(request):
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    popular = Rating.objects.all().order_by('-star').values('product')[:6]
    ids = []
    results = []
    for elem in popular:
        ids.append(elem.get('product', None))
    products = products.filter(id__in=ids)

    if request.GET.get("min_price") and request.GET.get("max_price"):
        min_price = request.GET["min_price"]
        max_price = request.GET["max_price"]
        results = products.filter(price__range=(int(min_price), int(max_price)))
        if not results:
            products = None

    return render(request, "shop/product/popular.html", {"categories": categories, "results": results, "products": products,})


def product_list(request, category_slug=None):
    category = None
    ordered = None
    categories = Category.objects.all()
    popular = Rating.objects.all().order_by('-star').values('product')[:6]
    ids = []
    for elem in popular:
        ids.append(elem.get('product', None))
    products = Product.objects.filter(id__in=ids, available=True)
    query = None
    results_search = []
    results = []

    if request.GET.get("search"):
        query = request.GET["search"]
        results_search = Product.objects.filter(name__iregex=query)
        products = None

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)
        ordered = sorted(products, key=operator.attrgetter('name'))
        if request.GET.get("min_price") and request.GET.get("max_price"):
            min_price = request.GET["min_price"]
            max_price = request.GET["max_price"]
            results = products.filter(price__range=(int(min_price), int(max_price)))
            if not results:
                products = None
                ordered = None

    return render(
        request,
        "shop/product/list.html",
        {
            "category": category,
            "categories": categories,
            "products": products,
            "query": query,
            "results_search": results_search,
            "results": results,
            "ordered": ordered
        },
    )


def product_detail(request, id, slug):
    categories = Category.objects.all()
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    rating_stars = Rating.objects.filter(product=product).values('star')
    cart_product_form = CartAddProductForm()
    favorite_product_form = FavoriteAddProductForm()
    star_form = RatingForm()
    sum = 0
    for elem in rating_stars:
        sum += elem.get('star', None)
    if sum != 0:
        avg = round(float(sum/len(rating_stars)), 2)
    else:
        avg = 0
    return render(
        request,
        "shop/product/detail.html",
        {"categories": categories, "product": product, "cart_product_form": cart_product_form, "favorite_product_form": favorite_product_form, "star_form": star_form, "avg": avg},
    )


@require_POST
def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def add_rating(request):
    form = RatingForm(request.POST)
    if form.is_valid():
        Rating.objects.update_or_create(
            ip=get_client_ip(request),
            product_id=int(request.POST.get("product")),
            defaults={'star_id': int(request.POST.get("star"))}
        )
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        return HttpResponse(status=400)

myshop/shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My shop{% endblock %}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style type="text/css">
        #logo{position:absolute;top:-180px;}
        /* Checkbox stars */
        .rating {
            overflow: hidden;
            vertical-align: bottom;
            display: inline-block;
            width: 155px;
            height: 30px;
        }
        
        .rating > input {
        opacity: 0;
        margin-right: -100%;
        }

        .rating > label {
        position: relative;
        display: block;
        float: right;
        background: url('/static/img/star-off-big.png');
        background-size: 30px 30px;
        }

        .rating > label:before {
            display: block;
            opacity: 0;
            content: '';
            width: 30px;
            height: 30px;
            background: url('/static/img/star-on-big.png');
            background-size: 30px 30px;
            transition: opacity 0.2s linear;
        }

        .rating > label:hover:before,  .rating > label:hover ~ label:before,  .rating:not(:hover) > :checked ~ label:before { opacity: 1; }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container">
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav nav-fill" style="width: 65%;">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:about' %}">О нас</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:delivery' %}">Доставка и оплата</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:contacts' %}">Контакты</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:discounts' %}">Акции</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <header>
        <div class="container" style="height: 30vh;">
            <div class="row align-items-center" style="height: 100%;">
                <div class="col-md-7">
                    <ul class="list-inline">
                        <li class="list-inline-item text-center" style="width: 30%; margin-right: 1%;">
                            <ul class="list-unstyled">
                                <li>+7 777 777 77 77</li>
                                <li>+7 777 777 77 77</li>
                            </ul>
                        </li>
                        <li class="list-inline-item text-center" style="width: 30%; margin-right: 1%;">
                            Рабочее время: 11:00-21:00
                        </li>
                        <li class="list-inline-item text-center" style="width: 30%; margin-right: 1%;">
                            10 минут от метро Серпуховская
                        </li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <div id="logo">
                        <a href="/">
                            <img src="{% static 'img/mylogo.png' %}">
                        </a>
                    </div>
                </div>
                <div class="col-md-2">
                    {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                            <a class="nav-link text-center text-secondary" href="{% url 'cart:cart_detail' %}">
                                <img src="{% static 'img/cart.png' %}" alt="Корзина" style="width: 40%;">
                                Корзина <span class="badge badge-secondary">{{ total_items }}</span>
                            </a>
                        {% else %}
                            <a class="nav-link text-center text-secondary" href="{% url 'cart:cart_detail' %}">
                                <img src="{% static 'img/cart.png' %}" alt="Корзина" style="width: 40%;">
                                Корзина пуста
                            </a>
                        {% endif %}
                    {% endwith %}
                    <a class="nav-link text-center text-secondary" href="{% url 'favorite:favorite_detail' %}">
                        <img src="{% static 'img/favorites.png' %}" alt="Избранное" style="width: 40%;">
                        Избранное
                    </a>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <nav class="navbar navbar-expand-md" style="width: 100%;">
                <ul class="navbar-nav nav-fill" style="width: 100%;">
                    <li class="nav-item dropdown">
                        <button type="button" class="btn btn-link btn-lg text-dark dropdown-toggle" data-toggle="dropdown">
                            Категории
                        </button>
                        <ul class="unstyled dropdown-menu" style="height: 50vh; overflow-y: scroll;">
                            {% for c in categories %}
                                <li class="list-group-item" {% if category.slug == c.slug %}class="selected"{% endif %}>
                                    <a href="{{ c.get_absolute_url }}" class="text-dark">{{ c.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="{% url 'shop:fandom_list' %}">Фандомы</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="{% url 'shop:popular_list' %}">Популярное</a>
                    </li>
                    <li class="nav-item col-md-6">
                        <form action="{% url 'shop:search' %}" class="form-inline my-2 my-lg-0" method="get">
                            <div class="input-group col-md-12">
                                <input name="search" type="" class="form-control mr-sm-2" placeholder="Поиск">
                                <input type="image" src="{% static 'img/search.png' %}" style="width: 50px;">
                            </div>
                        </form>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

    <div id="content" style="margin-top: 1%; margin-bottom: 4%;">
        {% block content %}
        {% endblock %}
    </div>

    <footer style="margin-top: 1%; margin-bottom: 4%;">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-lg-3 mb-md-0 mb-4">
                    <h5 class="footer-heading d-flex">Контакты</h5><br>
                    <ul class="list-unstyled">
                        <li class="py-2 d-block h6">Адрес: Москва, улица Большая Полянка, 1/3</li>
                        <li class="py-2 d-block h6">
                            <ul class="list-unstyled">
                                <li>+7 777 777 77 77</li>
                                <li>+7 777 777 77 77</li>
                            </ul>
                        </li>
                        <li class="py-2 d-block h6">Рабочее время: 11:00-21:00</li>
                    </ul>
                </div>
                <div class="col-md-3 col-lg-3 mb-md-0 mb-4">
                    <h5 class="footer-heading align-items-center">Дополнительно</h5><br>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'shop:contacts' %}" class="py-2 d-block h6 text-dark">Обратная связь</a></li>
                        <li><a href="{% url 'shop:discounts' %}" class="py-2 d-block h6 text-dark">Акции</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-lg-3 mb-md-0 mb-4">
                    <h5 class="footer-heading align-items-center">Информация</h5><br>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'shop:about' %}" class="py-2 d-block h6 text-dark">О нас</a></li>
                        <li><a href="{% url 'shop:delivery' %}" class="py-2 d-block h6 text-dark">Доставка и оплата</a></li>
                        <li><a href="{% url 'shop:delivery' %}" class="py-2 d-block h6 text-dark">Возврат товара</a></li>
                    </ul>
                </div>
                <div class="col-md-2 col-lg-3">
                    <h5 class="footer-heading d-flex align-items-center">Соцсети</h5>
                    <div class="row no-gutters">
                        <div class="col-3 col-md-5">
                            <a href="#"><img style="width: 61%;" src="{% static 'img/icons/inst_icon.png' %}" alt=""></a>
                        </div>
                        <div class="col-3 col-md-5">
                            <a href="#"><img style="width: 58%;" src="{% static 'img/icons/vk_icon.png' %}" alt=""></a>
                        </div>
                        <div class="col-3 col-md-5">
                            <a href="#"><img style="width: 61%;" src="{% static 'img/icons/telegram_icon.png' %}" alt=""></a>
                        </div>
                        <div class="col-3 col-md-5">
                            <a href="#"><img style="width: 65%;" src="{% static 'img/icons/whatsapp_icon.png' %}" alt=""></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>